# Generated by Selenium IDE
import pytest
import time
import json
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogout(self):
    self.driver.get("http://localhost:5000/auth/profile")
    self.driver.set_window_size(1050, 944)
    elements = self.driver.find_elements(By.LINK_TEXT, "Logout")
    if len(elements) > 0 :
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        elements = self.driver.find_elements(By.LINK_TEXT, "Logout")
        assert len(elements) == 0
    self.driver.save_screenshot(f'{sys._getframe().f_code.co_name}.png') # generates a png file with the name of the test function being called

  
