"""added table role

Revision ID: 769acbbe1cc3
Revises: fb7628c1d167
Create Date: 2024-09-16 13:40:07.277813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769acbbe1cc3'
down_revision = 'fb7628c1d167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
